### ISSUE TITLE
TensorFlow.Binding

### ISSUE THREAD

**Issue by SkyQuant** [SciSharp/SciSharp-Stack-Examples#11]
![image](https://user-images.githubusercontent.com/6097882/76147439-3bf8ef00-60ad-11ea-848d-2e30657f5ae3.png)

How to solve this reference?

**Comment by SkyQuant** [comment]
And also how to setup and bind TensorFlow 2.0/2.1? There is v1.15 only in NuGet repository.

**Comment by javageek68** [comment]
I'm running into the same issue.  I downloaded the project and followed the instructions to run it.  The TensorFlowNET.Examples project seems to reference the TensorFlow.Binding project which does not appear to exist.

**Comment by Oceania2018** [comment]
Please clone this project as well: https://github.com/SciSharp/TensorFlow.NET

**Comment by javageek68** [comment]
That's cool.  I am able to run it now.  Are all of the examples supposed to work?  #1 Hello World ran fine.  But, all the rest seemed to error out.  Most of them were null exceptions.

**Comment by Oceania2018** [comment]
@javageek68 `master` branch is WIP based on tensorflow 2. Please use this branch https://github.com/SciSharp/SciSharp-Stack-Examples/tree/tf.net-1.15 for production.

**Comment by javageek68** [comment]
Thanks!  That works much better.  The work you guys did is really incredible!
