### ISSUE TITLE
The majority of the examples crash

### ISSUE THREAD

**Issue by Mattias-NCVIB** [SciSharp/SciSharp-Stack-Examples#16]
The first four examples work, the rest crash on two different computers - both running with fresh VS2019 installs. Is that to be expected, or did I miss something? Are we in between two working releases?

Example: Hello World in 0,0848558s is OK!
Example: Basic Operations in 0,1338481s is OK!
Example: NN XOR in 0,000847s is OK!
Example: Linear Regression in 1,1675918s is OK!
Example: Logistic Regression is Failed!
Example: Naive Bayes Classifier is Failed!
Example: Nearest Neighbor is Failed!
Example: Digits Recognition Neural Network is Failed!
Example: MNIST CNN is Failed!
Example: MNIST RNN is Failed!
Example: MNIST LSTM is Failed!
Example: CnnInYourOwnData is Failed!
Example: Fully Connected Neural Network is Failed!
Example: Convert TensorFlow Model to OpenCv is Failed!
Example: Image Recognition Inception is Failed!
Example: Retrain Classifier With InceptionV3 is Failed!
Example: Object Detection is Failed!
Example: CNN Text Classification is Failed!
Example: Word2Vec is Failed!

I'm including the log file.

[output.txt](https://github.com/SciSharp/SciSharp-Stack-Examples/files/4763415/output.txt)

**Comment by fwaris** [comment]
same here (I only tried a few). Hopefully someone is able to help as we can't learn Tensorflow.Net fast enough unless the examples are working

**Comment by Oceania2018** [comment]
Check the latest code push. It should work for 1-5 examples.

**Comment by mfagerlund** [comment]
I can confirm that the first five now work, it would probably avoid some confusion if it was made clear what tests are currently expexted to test, perhaps with "(expected to fail)" in the name, but perhaps that's not needed.

Example: Hello World in 0,0652704s is OK!
Example: Basic Operations in 0,1059289s is OK!
Example: NN XOR in 14,654874s is OK!
Example: Linear Regression in 13,9943392s is OK!
Example: Logistic Regression in 7,6043787s is OK!
Example: Naive Bayes Classifier is Failed!
Example: Nearest Neighbor is Failed!
Example: Digits Recognition Neural Network is Failed!
Example: MNIST CNN is Failed!
Example: MNIST RNN is Failed!
Example: MNIST LSTM is Failed!
Example: CnnInYourOwnData is Failed!
Example: Fully Connected Neural Network is Failed!
Example: Convert TensorFlow Model to OpenCv is Failed!
Example: Image Recognition Inception is Failed!
Example: Retrain Classifier With InceptionV3 is Failed!
Example: Object Detection is Failed!
Example: CNN Text Classification is Failed!
Example: Word2Vec is Failed!

**Comment by lucifer8900** [comment]
Please use the 1.15 branch。ALL。SciSharp-Stack-Examples AND TensorFlow.NET
