### ISSUE TITLE
NullReferenceException thrown in keras.preprocessing.image_dataset_from_directory 

### ISSUE THREAD

**Issue by pardont** [SciSharp/SciSharp-Stack-Examples#27]
Running ImageClassificationKeras example, the keras.preprocessing.image_dataset_from_directory  thrown NullReferenceException.

![image](https://user-images.githubusercontent.com/2252587/100434083-f1098680-30d6-11eb-8e0e-b240d9a844b6.png)

**Comment by Oceania2018** [comment]
Duplicate with https://github.com/SciSharp/SciSharp-Stack-Examples/issues/23
