### ISSUE TITLE
Mnist Model Loader stuck at loading training images

### ISSUE THREAD

**Issue by Zduniusz** [SciSharp/SciSharp-Stack-Examples#29]
MnistModelLoader is stuck at loading images. I tried installing some nuget mnist packages but that didn't help. I tried deleting downloaded file but that also didn't make any diffrence. I tiried also running exe on VM, no change.
![2020-12-22 03_25_16-Window](https://user-images.githubusercontent.com/31253374/102841502-58c89e00-4405-11eb-952e-0d2c2444a5e5.png)

**Comment by Esther2013** [comment]
Please try latest release.
