### ISSUE TITLE
Download the project that cannot run C #.

### ISSUE THREAD

**Issue by bbhxwl** [SciSharp/SciSharp-Stack-Examples#49]
很多错误，这是其中之一。
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	CS0111	类型“CIFAR10_CNN”已定义了一个名为“Run”的具有相同参数类型的成员	TensorFlowNET.Examples	C:\Users\47013\Desktop\临时\SciSharp-Stack-Examples-master\src\TensorFlowNET.Examples\ImageProcessing\ToyResNet.cs	43	活动

**Comment by Oceania2018** [comment]
请重新下载新代码，应该是没问题的。
