### ISSUE TITLE
Lots of exceptions

### ISSUE THREAD

**Issue by kasozivincent** [SciSharp/SciSharp-Stack-Examples#53]
Unfortunately, none of the examples work without throwing exceptions. The documentation in VS Intellisense is also not nice.
![image](https://user-images.githubusercontent.com/56205969/119374636-b8c3b900-bcb1-11eb-8b9b-ad8711f75f25.png)
This is just of the annoying exceptions. Do I have to first install TensorFLow to get it working??? And which assemblies are we supposed to install? Thanks

**Comment by Oceania2018** [comment]
The error in the screenshot means the data type doesn't match. It should input `float` matrix.
