### ISSUE TITLE
The type 'Tensor' does not define the field, constructor or member 'asTensor'.

### ISSUE THREAD

**Issue by manpil** [SciSharp/SciSharp-Stack-Examples#58]
As I was trying to reproduce the fully connected keras example in F# i encountered  the following error:
The type 'Tensor' does not define the field, constructor or member 'asTensor'.
Has anyone an idea why?
<img width="846" alt="issue" src="https://user-images.githubusercontent.com/50042145/129265365-5d12476d-123e-4f2a-9e71-3b48a4edae29.png">

**Comment by Oceania2018** [comment]
Is the `x_train` `NDArray`? if yes, you can use `tf.constant(x_train)` to convert it as tensor.

**Comment by manpil** [comment]
Not quite, but thanks for the push in the right direction. I now figured it out.
`x_train` was already a tensor, `y_train` was an `NDArray.`
Another problem was the `.asTensors` method as seen in this screenshot
![image](https://user-images.githubusercontent.com/50042145/129385840-a2805d78-1c1d-4c57-88f5-bf27277eb44f.png)
I used `Tensors.op_Implicit inputs` to convert `Tensors` to `Tensor` and vice verca.
Should I close the issue or open a pull request with the changes?
I am not sure if I fully understand the repo yet or if I just forgot to include other important files

**Comment by Oceania2018** [comment]
If you make it work, you can PR the fix.

**Comment by manpil** [comment]
Nevermind, I was missing an important file for it to build. The code works as it is. I am closing the issue.
Thank you for your help.

**Comment by dedale** [comment]
@Oceania2018 @manpil  not sure if this relates to the examples I ported to F#. C# code and samples make great use of automatic type convertors which are not implicitly available in F#. That's why I added many extra type methods to simplify the code.
