### ISSUE TITLE
Dictionary with members count or item count?

### ISSUE THREAD

**Issue by sascha-schwegelbauer** [SciSharp/SciSharp-Stack-Examples#60]
Hi!

I was just stepping through the example - one question regarding https://github.com/SciSharp/SciSharp-Stack-Examples/blob/bedbd284058774883229452f2c0e781dbe4c137a/src/TensorFlowNET.Examples/TextProcessing/DataHelpers.cs#L33

Isn't it a typo that just the current members count of the dictionary is put into it?
My proposal would be:
`
word_dict[word.Word] = word.Count;
`

If it's just a wrong interpretation of me - ignore this and nevermind.

Regards
Sascha

PS: I think @Oceania2018 should be mentioned here :-)

**Comment by Oceania2018** [comment]
@sascha-schwegelbauer I don't think it's a typo, it's encoding the dictonary as the incremental order.

**Comment by sascha-schwegelbauer** [comment]
> @sascha-schwegelbauer I don't think it's a typo, it's encoding the dictonary as the incremental order.

Do you know why a dictionary was used if the absolute count is not needed?
For just storing the order, I think a List<string> would also be okay?

**Comment by Oceania2018** [comment]
It's just to make an `ID` to every word in the dictionary.

**Comment by sascha-schwegelbauer** [comment]
> It's just to make an `ID` to every word in the dictionary.

Thanks for the fast answers!
