### ISSUE TITLE
循环第一次耗时比后面几次长

### ISSUE THREAD

**Issue by zi-done** [SciSharp/SciSharp-Stack-Examples#65]
https://github.com/SciSharp/SciSharp-Stack-Examples/blob/master/src/TensorFlowNET.Examples/ImageProcessing/ImageRecognitionInception.cs
![image](https://user-images.githubusercontent.com/26201484/156174458-fbd22386-4d13-49d9-9e87-df5e2efb46f4.png)
我发现循环第一次的耗时永远比后面几次时间长，想问一下这是tf.Session().run()初次运行导致的吗

**Comment by Oceania2018** [comment]
应该是的。
