### ISSUE TITLE
TrainableVariables missing in NuGet-packages - not able to run example using NuGet-packages, only by compiling full source

### ISSUE THREAD

**Issue by Darlanio** [SciSharp/SciSharp-Stack-Examples#71]
See public github repository for example:
https://github.com/Darlanio/SciSharp_TensorFlowNet_Missing_TrainableVariables

I was able to compile the SciSharp-Stack-Examples and run the GAN-example without too much trouble, by incorporating all necessary repositories from SciSharp into the same solution. 

However, using the NuGet packages, the TrainableVariables referred to on lines 163-167 in the file
https://github.com/SciSharp/SciSharp-Stack-Examples/blob/master/src/TensorFlowNET.Examples/GAN/MnistGAN.cs
will not be found.

One other thing that is missing is the ToBitmap() in NDArray, line 227. I wrote another SaveImage() to bypass this problem.

Since the TrainableVariables are available in the SciSharp-repositories, I guess this will be fixed with the next version of the NuGet-packages?

**Comment by Oceania2018** [comment]
Just updated. Try to upgraede.

**Comment by Darlanio** [comment]
There seems to be something wrong still with the nuget packages. I upgraded to
SciSharp.Tensorflow.Redist-Windows-GPU 2.10.0
TensorFlow.Keras 0.10.0
TensorFlow.NET 0.100.0

and use the code from the example MnistGAN.cs

All code compiles and run without error, but no improvement is visible in the output, while the same MnistGAN.cs file with only minor modifications shows clear improvements for each epoch.

I will post my code later this week in case there is something wrong there, but this is an indication that there might be something wrong. Do anyone else notice anything?

**Comment by Darlanio** [comment]
Updated nugets, but example still not working. Maybe I have done something wrong?

https://github.com/Darlanio/TensorFlowNetUpdatedGAN

I have now tried it both on CPU and GPU on two different computers. When using the full set of repositories from SciSharp, the code in the example (MnistGAN.cs) works just fine. When using it with the nuget-packages, it is not improving - code runs but without learning to generate any written figures.

**Comment by Darlanio** [comment]
![AboveWithNuGetPackagesBelowWithSourceCompiledRepositories](https://user-images.githubusercontent.com/11479716/214292303-acf5d736-18f4-49d2-bd07-1311f318264a.jpg)

Above is the non-existing progress when using NuGet Packages - might be a bug in my code that is available at https://github.com/Darlanio/TensorFlowNetUpdatedGAN

Below is the progress using code compiled from SciSharp repositories. It works just fine with that code. Not sure what is the difference.

**Comment by Darlanio** [comment]
Maybe I should open a new ticket/issue?

**Comment by Darlanio** [comment]
Only a few rows of code are different:
![image](https://user-images.githubusercontent.com/11479716/214294946-412d6708-6704-4001-b76a-1e8540074be0.png)

**Comment by Darlanio** [comment]
I will let this remain closed and create a new issue.

**Comment by Darlanio** [comment]
The error can be seen with

            Console.WriteLine("D:" + D.TrainableVariables.Count());
            Console.WriteLine("G:" + G.TrainableVariables.Count());

D reports 12
G reports 8 with SciSharp-repositories, but 0 with NuGets.
