### ISSUE TITLE
Something is wrong with the updated nuget packages

### ISSUE THREAD

**Issue by Darlanio** [SciSharp/SciSharp-Stack-Examples#72]
There seems to be something wrong with the nuget packages. 

I upgraded to
SciSharp.Tensorflow.Redist-Windows-GPU 2.10.0
TensorFlow.Keras 0.10.0
TensorFlow.NET 0.100.0

and use the code from the example MnistGAN.cs
in https://github.com/SciSharp/SciSharp-Stack-Examples/tree/master/src/TensorFlowNET.Examples/GAN

Code compiles, but:

![214292303-acf5d736-18f4-49d2-bd07-1311f318264a](https://user-images.githubusercontent.com/11479716/214574158-abd83d1f-9bbf-49ef-9927-6bf1706d192a.jpg)

There is only a few changes to the code in MnistGAN.cs to allow it to compile:
![214294946-412d6708-6704-4001-b76a-1e8540074be0](https://user-images.githubusercontent.com/11479716/214574234-8d438133-fa0f-495d-8829-5d83b6bd438f.png)

What is strange is that the code works just fine if code is compiled using all the source from SciSharp repositories, but when using the NuGet packages, it fails to improve.

Let me know if I made an error. My code is available here:
https://github.com/Darlanio/TensorFlowNetUpdatedGAN

**Comment by Darlanio** [comment]
Related to issue: https://github.com/SciSharp/SciSharp-Stack-Examples/issues/71#issuecomment-1383432284

**Comment by Darlanio** [comment]
The error can be seen with

        Console.WriteLine("D:" + D.TrainableVariables.Count());
        Console.WriteLine("G:" + G.TrainableVariables.Count());

D reports 12
G reports 8 with SciSharp-repositories, but 0 with NuGets.

**Comment by Darlanio** [comment]
I have also tested to copy the DLL-files Tensorflow.Binding.dll and Tensorflow.Keras.dll from the solution using SciSharp-repositories into the folder of the NuGet-packaged compiled binaries, replacing those same dll-files - and then it works. Clearly something is wrong with the nugets now published.

Since it only affects the generator, I guess it relates to Sequential Model somehow.

**Comment by Oceania2018** [comment]
> The error can be seen with
> 
> ```
>     Console.WriteLine("D:" + D.TrainableVariables.Count());
>     Console.WriteLine("G:" + G.TrainableVariables.Count());
> ```
> 
> D reports 12 G reports 8 with SciSharp-repositories, but 0 with NuGets.

The TrainableVariables is a problem. I'll take a look.
